// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel WaveCompute

// Height information
RWStructuredBuffer<float> heights;
StructuredBuffer<float3> vertices;
uint num_of_vertices;
float radius;

[numthreads(1024,1,1)]
void WaveCompute (uint id : SV_DispatchThreadID) {
    if (id >= num_of_vertices) { return; }

    // TODO: wave compute

    heights[id] = radius;
}
